spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.156:3333

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"
        #PREFER_HOST_MODE