server:
  port: 80
spring:
  application:
    name: springcloud-client80
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    instance-id: ${spring.application.name}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:7001/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
