server:
  port: 8002
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:123456@eureka7001.com:7001/eureka/,http://admin:123456@eureka7002.com:7002/eureka/,http://admin:123456@eureka7003.com:7003/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true

#server:
#  port: 8001
#
#spring:
#  application:
#    name: cloud-payment-service
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456
#  devtools:
#    livereload:
#      enabled: true
#      ## 设置哪些资源变动后不触发热部署，会覆盖默认的exclude内容（资源不会触发重启，但会触发实时重新加载）
#      # exclude: WEB-INF/**,static/**
#      ## 监控额外的路径（优先于exclude）
#      # additional-paths: src/main/java
#eureka:
#  instance:
#    hostname: localhost #eureka服务端的实例名称
#  client:
#
#    #    将自己注册进EurekaServer
#    register-with-eureka: true
#    #    是否从EurekaServer抓取已有的注册信息，默认为ture。单节点无所谓，集群必须设置为ture才能配合ribbon使用负载均衡
#    servcieUrl:
#      defaultZone: http://localhost:7001/eureka
##    fetchRegistry: true
