spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.48:8848

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"
        #PREFER_HOST_MODE